# -*- coding: utf-8 -*-
"""TrabalhoIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sCN_ffX-_D5mqQSKRwyeZI_GpRy42nEo
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_predict
from sklearn import linear_model
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor
import warnings
warnings.filterwarnings("ignore", category=UserWarning)

"""# 1.   Importando dataset

---


"""

df = pd.read_csv("CO2 Emissions_Canada.csv")

"""# 2.   Conhecendo e tratando dados

---




"""

df.dtypes

df.head()

print(f"Duplicatas: {df.duplicated().sum()}")

df = df.drop_duplicates()

df = pd.get_dummies(df, drop_first=True)
df.head()

df.count()

"""

# 3.   Visualizando uma das features

---



"""

plt.scatter(df['Fuel Consumption City (L/100 km)'], df['CO2 Emissions(g/km)'])
plt.xlabel("Consumo de combustivel cidade")
plt.ylabel("Emissao CO2")
plt.show()

"""

# 4.  Criando funções

---



"""

model = linear_model.LinearRegression()

def run(X, y, test_split: float, crossValidation: bool):
  if(crossValidation):
    y_pred = cross_val_predict(model, X, y, cv = 5)
    y_true = y
  else:
    X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=test_split)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_true = y_test

  return { 'pred': y_pred, 'true':y_true}

def calc_metricas(results: dict):
  mae = mean_absolute_error(results['true'], results['pred'])
  mse = mean_squared_error(results['true'], results['pred'])
  rmse = np.sqrt(mse)
  r2 = r2_score(results['true'], results['pred'])
  metricas = {
      'MAE': mae,
      'MSE': mse,
      'RMSE': rmse,
      'R²': r2
  }
  print(metricas)

def plot_acc(y_test, y_pred, barWidth: float):
  n = len(y_test)
  indices = np.arange(n)

  plt.figure(figsize=(12,6))
  plt.plot(indices, y_test, label='Valor Real', color='navy', linewidth=2)

# Plot valores previstos - área preenchida com transparência
  plt.plot(indices, y_pred, label='Valor Previsto', color='lightgreen', linewidth=2)

  plt.xlabel('Amostras')
  plt.ylabel('Valores')
  plt.legend()
  plt.show()

from sklearn.metrics import accuracy_score
rfr = RandomForestRegressor(random_state=42)

#Performa um pouco melhor sem a validação cruzada...

def rfr_run(X,y, test_split: float, crossValidation: bool):
    if(crossValidation):
      y_pred = cross_val_predict(rfr, X, y, cv = 5)
      y_true = y

    else:
      X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=test_split,random_state=42)
      rfr.fit(X_train, y_train)
      y_pred = rfr.predict(X_test)
      y_true = y_test
    return {'pred': y_pred, 'true': y_true}

"""

# 5.   Treinos

---



"""

X = df.drop(columns=['CO2 Emissions(g/km)'])
y = df['CO2 Emissions(g/km)']

results = run(X, y, 0.3, True)
calc_metricas(results)
plot_acc(results['true'], results['pred'], 0.4)

""" **Resultados usando Random Forest Regressor**"""

resultados_rfr = rfr_run(X,y, 0.3, True)
calc_metricas(resultados_rfr)
plot_acc(resultados_rfr['true'], resultados_rfr['pred'], 0.4)