# -*- coding: utf-8 -*-
"""trabalhoIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fHZL4N71LUIXc8x0ZboSFAKb0Tyjjn49
"""

# Instalação da biblioteca para Optimum-Path Forest (OPF)
!pip install opfython

import cv2
import numpy as np
import os
import glob
import pandas as pd
from skimage.morphology import skeletonize
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

# Importando OPF
from opfython.models import SupervisedOPF

def extract_masks(image):
    """
    Separa o Template (ET) e o Traço Manuscrito (HT) baseado nas cores descritas no artigo.
    ET é preto/cinza. HT é azul (caneta).
    """
    # Converter para RGB (OpenCV carrega como BGR)
    img_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    R, G, B = img_rgb[:,:,0], img_rgb[:,:,1], img_rgb[:,:,2]

    # Equação (1) do artigo: Extração do Template (ET)
    # Pixels escuros (R, G, B < 100) são o template
    mask_et = np.where((R < 100) & (G < 100) & (B < 100), 1, 0).astype(np.uint8)

    # Equação (2) do artigo: Extração do Traço (HT)
    # Diferença entre canais para detectar a cor azul da caneta
    # Condição simplificada baseada no artigo: O azul deve predominar ou haver diferença significativa
    # O artigo usa |R-G|<40 e |R-B|<40 para filtrar cinzas, o resto é cor.
    # Aqui adaptamos para pegar o traço azul típico.
    mask_ht_raw = np.where((np.abs(R.astype(int) - G.astype(int)) > 20) |
                           (np.abs(R.astype(int) - B.astype(int)) > 20), 1, 0).astype(np.uint8)

    return mask_et, mask_ht_raw

def get_skeleton(binary_mask):
    """Aplica o algoritmo de afinamento (Zhang-Suen ou similar)"""
    return skeletonize(binary_mask).astype(np.uint8)

def ray_cast_sampling(et_skel, ht_skel, center):
    """
    Lança 360 raios do centro e encontra interseções com ET e HT.
    Baseado na Fig 6 e Seção 2.2.2 do artigo.
    """
    h, w = et_skel.shape
    radii_et = []
    radii_ht = []

    # 360 graus
    for angle in range(0, 360):
        theta = np.deg2rad(angle)
        # Vetor direção
        dx = np.cos(theta)
        dy = np.sin(theta)

        r_et_point = 0
        r_ht_point = 0

        # Marcha do raio (Ray marching simples)
        # Vamos até a borda da imagem
        max_dist = np.sqrt(h**2 + w**2) / 2
        for r in range(1, int(max_dist)):
            x = int(center[0] + r * dx)
            y = int(center[1] + r * dy)

            if x < 0 or x >= w or y < 0 or y >= h:
                break

            # Verifica interseção
            if et_skel[y, x] > 0:
                r_et_point = r
            if ht_skel[y, x] > 0:
                r_ht_point = r

        # Apenas considera se o raio cruzou AMBOS (Fair sampling - Eq 3 texto)
        if r_et_point > 0 and r_ht_point > 0:
            radii_et.append(r_et_point)
            radii_ht.append(r_ht_point)

    return np.array(radii_et), np.array(radii_ht)

def compute_features(radii_et, radii_ht):
    """Calcula as 9 features (f1 a f9) baseadas nas listas de raios."""
    if len(radii_et) == 0: return np.zeros(9)

    diff = radii_ht - radii_et
    abs_diff = np.abs(diff)

    # f1: RMS
    f1 = np.sqrt(np.mean(diff**2))
    # f2: Max diff
    f2 = np.max(abs_diff)
    # f3: Min diff
    f3 = np.min(abs_diff)
    # f4: Std dev diff
    f4 = np.std(diff)

    # Cálculo de Tremor (MRT) - Eq (6)
    # O artigo usa d=10 como deslocamento
    d = 10
    tremor_vals = []
    if len(radii_ht) > d:
        for i in range(d, len(radii_ht)):
            tremor = np.abs(radii_ht[i] - radii_ht[i-d]) # Simplificação do termo de tremor
            tremor_vals.append(tremor)
        tremor_vals = np.array(tremor_vals)
    else:
        tremor_vals = np.array([0])

    f5 = np.mean(tremor_vals) # MRT
    f6 = np.max(tremor_vals)
    f7 = np.min(tremor_vals)
    f8 = np.std(tremor_vals)

    # f9: Mudanças de sinal (Zero crossings)
    signs = np.sign(diff)
    f9 = np.sum(np.abs(np.diff(signs))) / 2

    return [f1, f2, f3, f4, f5, f6, f7, f8, f9]

# Defina os caminhos das pastas
path_control = "MeanderControl"
path_patient = "MeanderPatients"

data = []
labels = [] # 0 = Control, 1 = Parkinson

def process_folder(folder_path, label):
    if not os.path.exists(folder_path):
        print(f"Pasta não encontrada: {folder_path}")
        return

    for filename in os.listdir(folder_path):
        if filename.lower().endswith(('.png', '.jpg', '.jpeg')):
            img_path = os.path.join(folder_path, filename)
            img = cv2.imread(img_path)

            if img is None: continue

            # 1. Pré-processamento
            # Redimensionar para padronizar (opcional, mas recomendado)
            img = cv2.resize(img, (400, 400))
            center = (200, 200)

            mask_et, mask_ht = extract_masks(img)

            # 2. Esqueletização
            skel_et = get_skeleton(mask_et)
            skel_ht = get_skeleton(mask_ht)

            # 3. Amostragem
            r_et, r_ht = ray_cast_sampling(skel_et, skel_ht, center)

            # 4. Features
            feats = compute_features(r_et, r_ht)

            data.append(feats)
            labels.append(label)

print("Processando Grupo de Controle...")
process_folder(path_control, 0)
print("Processando Grupo de Pacientes...")
process_folder(path_patient, 1)

# Criar DataFrame
df = pd.DataFrame(data, columns=[f'f{i}' for i in range(1, 10)])
y = np.array(labels)
X = df.values

# Normalização (Eq 7 do artigo)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print(f"Total de amostras processadas: {len(df)}")

# --- 1. INSTALAÇÃO E IMPORTAÇÕES ---
try:
    import opfython
except ImportError:
    !pip install opfython
    import opfython

import cv2
import numpy as np
import os
import pandas as pd
from skimage.morphology import skeletonize
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
from opfython.models import SupervisedOPF

# --- 2. FUNÇÕES DE VISÃO COMPUTACIONAL ---
def extract_masks(image):
    img_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    R, G, B = img_rgb[:,:,0], img_rgb[:,:,1], img_rgb[:,:,2]
    # Template (escuro)
    mask_et = np.where((R < 100) & (G < 100) & (B < 100), 1, 0).astype(np.uint8)
    # Traço (azul/diferente de cinza)
    mask_ht = np.where((np.abs(R.astype(int) - G.astype(int)) > 20) |
                       (np.abs(R.astype(int) - B.astype(int)) > 20), 1, 0).astype(np.uint8)
    return mask_et, mask_ht

def get_skeleton(binary_mask):
    return skeletonize(binary_mask).astype(np.uint8)

def ray_cast_sampling(et_skel, ht_skel, center):
    h, w = et_skel.shape
    radii_et, radii_ht = [], []
    for angle in range(0, 360):
        theta = np.deg2rad(angle)
        dx, dy = np.cos(theta), np.sin(theta)
        r_et_point, r_ht_point = 0, 0
        max_dist = np.sqrt(h**2 + w**2) / 2
        for r in range(1, int(max_dist)):
            x, y = int(center[0] + r * dx), int(center[1] + r * dy)
            if x < 0 or x >= w or y < 0 or y >= h: break
            if et_skel[y, x] > 0: r_et_point = r
            if ht_skel[y, x] > 0: r_ht_point = r
        if r_et_point > 0 and r_ht_point > 0:
            radii_et.append(r_et_point)
            radii_ht.append(r_ht_point)
    return np.array(radii_et), np.array(radii_ht)

def compute_features(radii_et, radii_ht):
    if len(radii_et) == 0: return np.zeros(9)
    diff = radii_ht - radii_et
    abs_diff = np.abs(diff)
    f1 = np.sqrt(np.mean(diff**2))
    f2 = np.max(abs_diff)
    f3 = np.min(abs_diff)
    f4 = np.std(diff)
    d = 10
    tremor_vals = np.abs(radii_ht[d:] - radii_ht[:-d]) if len(radii_ht) > d else np.array([0])
    f5 = np.mean(tremor_vals)
    f6 = np.max(tremor_vals)
    f7 = np.min(tremor_vals)
    f8 = np.std(tremor_vals)
    signs = np.sign(diff)
    f9 = np.sum(np.abs(np.diff(signs))) / 2
    return [f1, f2, f3, f4, f5, f6, f7, f8, f9]

# --- 3. CARREGAMENTO E PROCESSAMENTO (CRIA O X_TRAIN) ---
path_control = "MeanderControl"
path_patient = "MeanderGroup"
data, labels = [], []

def process_folder(folder_path, label):
    if not os.path.exists(folder_path):
        print(f"ALERTA: Pasta {folder_path} não encontrada!")
        return
    print(f"Lendo pasta: {folder_path}...")
    files = [f for f in os.listdir(folder_path) if f.lower().endswith(('.jpg', '.jpeg', '.png'))]
    for filename in files:
        img = cv2.imread(os.path.join(folder_path, filename))
        if img is None: continue
        img = cv2.resize(img, (400, 400))
        mask_et, mask_ht = extract_masks(img)
        r_et, r_ht = ray_cast_sampling(get_skeleton(mask_et), get_skeleton(mask_ht), (200, 200))
        data.append(compute_features(r_et, r_ht))
        labels.append(label)

process_folder(path_control, 0)
process_folder(path_patient, 1)

if len(data) == 0:
    print("ERRO: Nenhuma imagem processada. Verifique se as pastas estão no Colab.")
else:
    X = StandardScaler().fit_transform(pd.DataFrame(data).values)
    y = np.array(labels)

    # AQUI É ONDE O X_TRAIN É DEFINIDO
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
    print(f"Dados prontos: {len(X_train)} treino, {len(X_test)} teste.")

    # --- 4. CLASSIFICAÇÃO (COM BALANCEAMENTO) ---
    results = {}

    # Naive Bayes
    nb = GaussianNB()
    nb.fit(X_train, y_train)
    results['Naive Bayes'] = accuracy_score(y_test, nb.predict(X_test))

    # SVM (Balanced)
    svm = SVC(kernel='rbf', class_weight='balanced')
    svm.fit(X_train, y_train)
    y_pred_svm = svm.predict(X_test)
    results['SVM Balanced'] = accuracy_score(y_test, y_pred_svm)

    # Random Forest (Balanced)
    rf = RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42)
    rf.fit(X_train, y_train)
    results['Random Forest'] = accuracy_score(y_test, rf.predict(X_test))

    # OPF (Ajuste de labels 0->2)
    y_train_opf, y_test_opf = y_train.copy(), y_test.copy()
    y_train_opf[y_train_opf==0] = 2
    y_test_opf[y_test_opf==0] = 2
    opf = SupervisedOPF()
    opf.fit(X_train, y_train_opf)
    results['OPF'] = accuracy_score(y_test_opf, opf.predict(X_test))

    # --- RESULTADOS ---
    print("\n=== Resultados Finais ===")
    print(pd.DataFrame.from_dict(results, orient='index', columns=['Acurácia']))
    print("\n=== Matriz de Confusão (SVM) ===")
    print(confusion_matrix(y_test, y_pred_svm))
    print("\n=== Relatório (SVM) ===")
    print(classification_report(y_test, y_pred_svm, target_names=['Controle', 'Parkinson']))
